# Generated by Django 5.0.3 on 2024-03-21 07:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('women', 'Mujer'), ('man', 'Hombre')], max_length=10, null=True)),
                ('rfc', models.CharField(max_length=13)),
                ('curp', models.CharField(max_length=18)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_kind', models.CharField(choices=[('vacations', 'Vacaciones'), ('business_improvements', 'Mejoras de negocios'), ('debt_payment', 'Pago de deuda'), ('education', 'Educación'), ('event', 'Eventos'), ('other', 'Otro')], max_length=50)),
                ('amount', models.FloatField()),
                ('payment_interval', models.CharField(choices=[('month', 'Meses'), ('year', 'Años')], max_length=10)),
                ('payment_duration', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_loans', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='LoanPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente')], max_length=10)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.loan')),
            ],
            options={
                'verbose_name': 'Loan payment',
                'verbose_name_plural': 'Loans payments',
            },
        ),
    ]
