# Generated by Django 5.0.3 on 2024-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanpayments',
            name='status',
            field=models.CharField(choices=[('paid', 'Pagado'), ('pending', 'Pendiente')], default='pending', max_length=10),
        ),
    ]
