# Generated by Django 5.0.3 on 2024-04-03 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_loanpayments_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_date', models.DateField()),
                ('amount', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='customer.loan')),
            ],
            options={
                'verbose_name': 'Refund payment',
                'verbose_name_plural': 'Refund payments',
            },
        ),
    ]
